### ISSUE TITLE
how to pass arguments from view presented using "sheet" to background Parent view 

### ISSUE THREAD

**Issue by hankyungs** [interactord/LinkNavigator#11]
Is there a way to pass the result or a specific value to the parent view when closing a view that has been entered using the navigator.sheet method? And can this be done without reloading the parent view?

(sheet 방식으로 진입한 자식 뷰에서 일을 처리한 뒤, 닫힐때 부모뷰를 replace 또는 reload 하지 않고 어떤 값을 전달할 수 있는 방법이 있을까요?)

**Comment by interactord** [comment]
초창기 개발할때, 핸들러(handler)나 클로저(closure)를 이용하여 코드 내에서 콜백(callback)을 호출하는 방식을 사용했습니다. 그러나 이를 구현하고 사용해 보니 해당 작업에 최적의 해결책으로 보이지 않아서 결국 이들을 제거했습니다. 실제 경험상 콜백이 필요할 때는 SwiftUI 클로저를 대신 사용하는 것이 더 적합하고 효율적인 방법을 제공하여 원하는 기능을 더욱 잘 수행할 수 있었습니다.

(In the past, I had utilized handlers or closures to invoke callbacks in my code. However, when I attempted to implement and use them, they didn't seem like the optimal solution for the task at hand, so I ultimately removed them. In my practical experience, whenever a callback was necessary, I opted to use SwiftUI closures instead, as they provided a more suitable and efficient approach to achieve the desired functionality.)

**Comment by interactord** [comment]
캐시와 비슷한 공유 데이터를 이용해서 업데이트하고, 뷰의 루트에서 .onAppear를 이용해 데이터를 받아오는 방식으로 처리했습니다. 그러나 iPad에서는 fullSheet 이외에는 .onAppear가 호출되지 않는 문제가 있었습니다.

(I updated the data using shared data similar to cache, and implemented a method of retrieving the data using .onAppear in the view's root. However, there was an issue where .onAppear was not called except for fullSheet on iPad.)
