### ISSUE TITLE
sheet 후 fullSheet하면 sheet로 한번 나오고, 재시도 시 fullSheet로 나옵니다.

### ISSUE THREAD

**Issue by YangJinmo** [interactord/LinkNavigator#13]
sheet 후 fullSheet하면 sheet로 한번 나오고, 재시도 시 fullSheet로 나옵니다.

**Comment by interactord** [comment]
@YangJinmo 님 이슈 주셔서 감사합니다.
원인 분석후, 피드백 드리도록 하겠습니다.

**Comment by lks574** [comment]
> 

iOS 버전 및 기기 알려주시면 확인해보겠습니다.

**Comment by YangJinmo** [comment]
iPhone Xs
iOS: 16.1.1

iPhone 7
iOS: 15.7.1

iPhone SE 1
iOS: 15.7.4

Simulator: iPhone 14 Pro
macOS: 13.2.1(22D68)
Xcode: Version 14.2 (14C18)

입니다.

**Comment by interactord** [comment]
해당 문제와 관련하여 노력 중이며, 조금만 기다려주시면 감사하겠습니다. 불편을 드려 죄송합니다.

**Comment by interactord** [comment]
<img width="1101" alt="Screenshot 2023-04-20 at 1 45 33 PM" src="https://user-images.githubusercontent.com/47267960/233260676-de7b7166-4de3-4a39-8c8f-c417d9c2bf41.png">

원인을 찾았습니다. 
첨부된 스크린샷을 보면, 해당 코드를 삭제하면 이슈를 해결할 수 있습니다.
하지만 현재로서는 해당 코드를 삭제할 수 없습니다. 
해당 코드를 사용한 이유는 사용자가 Drag-Gesture를 사용하여 시트를 내렸을 때 이벤트를 받기 위해 설정한 값이기 때문입니다.
대부분의 사용자가 Drag-Gesture를 자주 사용하기 때문에 두 가지 방법 모두 충족하는 결과를 얻기 위해서는 시간이 조금 걸릴 것으로 예상됩니다.

@YangJinmo님 일단 이부분은 개선사항으로 태그를 바꾸도록 하겠습니다.

다시한번 더, 해당 이슈에 대해 해결하지 못한 부분에 대해서 죄송합니다.

**Comment by interactord** [comment]
@YangJinmo 님 해당 티켓은 @97chos 님이 수정하여 배포하였습니다.
버전을 0.7.1로 일단 올렸으니, 한번 테스트해보실 수 있을까요?

동일한 문제가 발생한다면, 해당 이슈를 다시 열어주시길 바랍니다.

감사합니다.

**Comment by YangJinmo** [comment]
잘 되는 것 같습니다! 고생하셨습니다! 감사합니다 ㅎㅎ 😄
