### ISSUE TITLE
ignoreSafeArea 미적용 문제

### ISSUE THREAD

**Issue by keyboardseokmin** [interactord/LinkNavigator#16]
ignoreSafeArea 를 사용해서 View 를 그릴때 (StatusBar 같은)
LinkNavigator 를 사용해서 호출한 화면은 ignoreSafeArea 가 적용이 되지 않는 문제가 있습니다.

**Comment by keyboardseokmin** [comment]
<img width="439" alt="스크린샷 2023-04-21 오전 9 31 52" src="https://user-images.githubusercontent.com/54494315/233513728-f252d36b-79f7-4e0e-a06d-466daf3eb591.png">
LinkNavigator 로 호출한 화면에서 Custom Alert 띄울시

**Comment by keyboardseokmin** [comment]
<img width="434" alt="스크린샷 2023-04-21 오전 9 33 07" src="https://user-images.githubusercontent.com/54494315/233513830-50ade475-d99e-422e-bc10-4b84f93ea655.png">
LinkNavigator 사용하지 않고 그냥 호출한 화면에서 Custom Alert 띄울시

**Comment by interactord** [comment]
@keyboardseokmin  님 이슈 공유해주셔서 감사합니다.

질문이 있습니다.
혹시 SwiftUI로 작업하셨나요?
만약에 작업하셨다면, var body부분 코드를 공유해주실 수 있을까요?

**Comment by keyboardseokmin** [comment]
struct PhoneNumberView: View {
    let navigator: LinkNavigatorType
    
    @EnvironmentObject var mainModel: MainModel
    @State private var isKeyboardVisible: Bool = false
    @State private var showingAlert: Bool = false
    @FocusState var isFocused: Bool
    
    var body: some View {
        HiddenNavBarView()
        
        VStack {
            Spacer().frame(height: 94)
            
            Text("num_guide_msg".localized())
                .font(.custom(Pretendard.SIX, size: 24))
                .foregroundColor(Colors.shared.text_main_black)
                .lineSpacing(2.88)
                .multilineTextAlignment(.center)
            
            Spacer().frame(height: 56.5)
            
            ZStack(alignment: .trailing) {
                TextField("num_textfield".localized(), text: $mainModel.phoneNumber)
                    .font(.custom(Pretendard.FIVE, size: 20))
                    .frame(height: 54)
                    .padding(EdgeInsets(top: 0, leading: 26, bottom: 0, trailing: 26))
                    .overlay(RoundedRectangle(cornerRadius: 10).strokeBorder(Colors.shared.textfield_border_gray, style: StrokeStyle(lineWidth: 1)))
                    .padding(EdgeInsets(top: 0, leading: 16, bottom: 0, trailing: 16))
                    .keyboardType(.numberPad)
                    .onChange(of: mainModel.phoneNumber) { newValue in
                        mainModel.phoneNumber = mainModel.setBarInPhoneNumber(newValue)
                    }
                    .focused($isFocused)
                
                Button(action:{
                    mainModel.phoneNumber = ""
                }) {
                    Image("TextFieldClear").tint(.clear)
                }
                .padding(10)
                .offset(x: -23)
            }
            
            Spacer()
            
            Button(action: {
                if (!mainModel.phoneNumber.isEmpty) {
                    showingAlert = true
                    isFocused = false
                }
            }) {
                Text("confirm".localized())
                    .font(.custom(Pretendard.SEVEN, size: 18))
                    .foregroundColor(Color.white)
                    .frame(maxWidth:.infinity, maxHeight:.infinity)
            }
            .frame(height: 54)
            .frame(maxWidth: .infinity)
            .background(mainModel.phoneNumber.isEmpty ? Colors.shared.button_gray : Colors.shared.button_blue)
            .cornerRadius(10)
            .padding(EdgeInsets(top: 0, leading: 16, bottom: isKeyboardVisible ? 5 : 48, trailing: 16))
            .onReceive(NotificationCenter.default.publisher(for: UIResponder.keyboardWillShowNotification)) { noti in
                withAnimation {
                    isKeyboardVisible = true
                }
            }
            .onReceive(NotificationCenter.default.publisher(for: UIResponder.keyboardWillHideNotification)) { noti in
                withAnimation {
                    isKeyboardVisible = false
                }
            }
        }
        .background()
        .onTapGesture {
            self.endTextEditing()
        }
        .dialog(isShowing: $showingAlert,
                cancelOnTapOutside: false
        ) {
            MyAlert(title: mainModel.phoneNumber,
                    message: "num_alert_content".localized(),
                    leftButtonName: "num_alert_cancel".localized(),
                    rightButtonName: "num_alert_next".localized(),
                    leftButtonAction: {
                        showingAlert = false
                        isFocused = true
                    },
                    rightButtonAction: {
                        showingAlert = false
                        navigator.replace(paths: ["MainView"], items: [:], isAnimated: true)
                    }
            )
        }
    }
}

**Comment by keyboardseokmin** [comment]
https://github.com/keyboardseokmin/ARTagiOS
에서 PhoneNumberView 에 있습니다 : )

**Comment by interactord** [comment]
@keyboardseokmin 님, 빠른 응답에 감사드립니다.

저희가 제작한 ignoreSafeArea를 적용한 화면 예시를 예제 소스로 공유하여 모든 분들이 확인할 수 있도록 하겠습니다.
조금만 기다려 주시면 감사하겠습니다.

**Comment by interactord** [comment]
@keyboardseokmin 님,
해당 이슈에 대해서는 문서와 예제를 업데이트하여 제공하겠습니다. 
예제코드(MVI/TCA)의 AppMain.swift에 있는 note를 참고해주세요.

**Comment by interactord** [comment]
만약 위 내용으로 문제를 해결할 수 없다면, 해당 이슈를 다시 열어주시고, 댓글로 남겨주세요.

@keyboardseokmin 좋은 주말보내세요~ Thank you~

**Comment by keyboardseokmin** [comment]
@interactord 감사합니다! 예제코드 참고해서 잘 적용했습니다 :)
