### ISSUE TITLE
새로운 데이터 플로우 방식을 제안합니다

### ISSUE THREAD

**Issue by HamTory06** [interactord/LinkNavigator#22]
안녕하세요. LinkNavigator와 SwiftUI로 여러 프로젝트를 진행하고 있는 주니어 개발자입니다. 

## 사용하면서 좋았던 점
다른 Coordinator 라이브러리를 써도 되지만 제가 LinkNavigator를 애용하는 이유는 빌드 타깃을 낮게 잡을 수 있고, 가장 큰 이유는 SwiftUI의 Alert을 아주 간단하게 사용할 수 있다는 점이 좋았기 때문입니다.

## 데이터 플로우 문제
현재 LinkNavigator로 다른 View에 데이터를 전달하려면 [String: String] 딕셔너리밖에 사용할 수 없습니다. 아무래도 URL 방식으로 작동하는 거라 이런 식으로 한계가 있을 수밖에 없지만, 그 한계가 데이터 플로우에서 좋지 않은 영향을 미칩니다.

제 프로젝트는 대부분 Codable struct를 모델로 사용하고 있습니다. 때문에 LinkNavigator로의 전환 시기에 이것을 모두 딕셔너리로 변환하는 과정이 가장 힘들고 어려웠습니다. 그래서 저는 임시방편으로 이런 extension을 만들어 Codable struct와 딕셔너리를 상호 변환해주는 메서드를 만들었습니다. 

> Struct -> [String: Any] -> [String: String] -> [String: Any] -> Struct
``` swift
extension Encodable {
    func encode() -> [String: String] {
        if let data = try? JSONEncoder().encode(self),
           let dictionary = try? JSONSerialization.jsonObject(with: data, options: .allowFragments) as? [String: Any] {
            var output = [String: String]()
            for (key, value) in dictionary {
                if let stringValue = value as? String {
                    output[key] = "\"(stringValue)\""
                } else if let numberValue = value as? NSNumber {
                    output[key] = numberValue.stringValue
                } else if let boolValue = value as? Bool {
                    output[key] = boolValue ? "true" : "false"
                } else {
                    output[key] = "(value)"
                }
            }
            return output
        } else {
            return [:]
        }
    }
}

extension Decodable {
    static func decode<T: Decodable>(_ from: [String: String]) -> T? {
        var input = [String: Any]()
        for (key, value) in from {
            if value.hasPrefix("\"") && value.hasSuffix("\"") {
                let stringValue = String(value.dropFirst().dropLast())
                input[key] = stringValue
            } else if let numberValue = Double(value) {
                if value.contains(".") {
                    input[key] = numberValue
                } else {
                    input[key] = Int(numberValue)
                }
            } else if let boolValue = Bool(value) {
                input[key] = boolValue
            } else {
                input[key] = value
            }
        }
        if let data = try? JSONSerialization.data(withJSONObject: input, options: .fragmentsAllowed),
           let output = try? JSONDecoder().decode(T.self, from: data) {
            return output
        } else {
            return nil
        }
    }
}
```

하지만 이것은 언제까지나 임시방편이지, 너무 불안정한 데다가 struct 안에 다른 struct가 있거나 배열이 있다면 변환할 수 없습니다.

그래도 제 프로젝트에서 LinkNavigator를 대체할 만한 Navigation 라이브러리가 마땅히 보이지 않는 것도 사실입니다. 솔직히 이 데이터 플로우 문제를 제외하면 완벽에 가까운 라이브러리라고 생각합니다.

## 제안
View간 데이터 전달에 딕셔너리 대신 struct를 사용할 수 있었으면 좋겠습니다. LinkNavigator의 기반을 변경하는 것이라 우려되기는 합니다. 하지만 이 문제만 해결하면 너무나도 장점이 뚜렷한 라이브러리이기 때문에 분명히 최고의 Navigation 라이브러리가 될 것을 믿어 의심치 않습니다.

**Comment by interactord** [comment]
먼저 링크네비게이터를 좋아해주셔서 너무 감사합니다.

저희도 이부분에 대해서 불편하지 않을까? 라는 의문을 가지고 있었습니다.

먼저 제안주신 encoded와 추가로 reflection 을 활용해서 저희쪽에서 한번 실험하고 공유드리도록 하겠습니다.

ps. 오래걸리지 않을거에요...

다시 한번 더 좋은 아이디어 제안주셔서 감사합니다.

**Comment by HamTory06** [comment]
답변 감사드립니다. 그런데 제가 이용한 방식은 중간에 [String: Any] -> [String: String] 변환을 거치는 거라.. 

```swift
struct Test {
    let id: Int
    let data: [Sample]
}
```

이런 식의 struct는 [String: String]으로 변환이 불가능하다는 점 알려드립니다.

**Comment by interactord** [comment]
공유감사합니다.

**Comment by interactord** [comment]
이번주에 도입전에 미리 공유드립니다.
@HamTory06 님이 공유해주신 아이디어로, Vapor에서 사용하고 있는 라이브러리를 iOS에 맞추어서 사용할 수 있도록 컨버팅한 라이브러리를 선공개 드려요..
https://github.com/interactord/URLEncodedForm

**Comment by HamTory06** [comment]
감사합니다. 잘 사용하겠습니다!
