### ISSUE TITLE
iPhone

### ISSUE THREAD

**Issue by Anagirotti** [interactord/LinkNavigator#23]

**Comment by interactord** [comment]
I apologize.
 We have deleted the code in the current document as we are preparing for the release of version 1.0.0.
 I have restored it, so please update to version 0.8.7

**Comment by interactord** [comment]
@Anagirotti 
Please double-check it once again.

**Comment by Anagirotti** [comment]
`[https://www.instagram.com/didueds?utm_source=qr](https://instagram.com/didueds?igshid=OGQ5ZDc2ODk2ZA==) `
