### ISSUE TITLE
Handling complex navigation use cases

### ISSUE THREAD

**Issue by farhanadji** [interactord/LinkNavigator#24]
Hello, I'm currently working on a complex project that involves several use cases for navigation and the initial view. I've encountered some scenarios:
![Screenshot 2023-09-21 at 20 01 27](https://github.com/interactord/LinkNavigator/assets/37927649/448bfc92-53e0-41a1-a2fb-d879d86aab4a)
1. For newly installed users, we need to present an onboarding process. Once they complete it, we should redirect them to the login page. If the user has already finished onboarding or hasn't logged in yet, we need to set the login page as the initial view. For this one, simply we can replace the root's viewControllers, right?
2. The confusion arises after a user logs in. In our logged-in state, the root view becomes UITabViewController/TabView and each item has its own navigation (just like TabLinkNavigator). How should we handle this situation? I've tried to assign the tabViewController to the root's view controllers (UINavigationController) but it ended up with duplicated navigation bars. It's also more challenging to determine which navigation controller is currently active. Do you have any suggestions for handling this scenario?
![Screenshot 2023-09-21 at 20 11 27](https://github.com/interactord/LinkNavigator/assets/37927649/3031e7b9-33d0-4a1b-a806-8727a8a9dbb6)

The first pict is the mockup of the flow to provide a comprehensive overview.
Thank you :)

**Comment by 97chos** [comment]
@farhanadji 
Hello! Thank you for adopting LinkNavigator in your project.

In the current implementation, there are two methods we can suggest for your consideration, both involving the use of a `CustomTabBar` to **`replace`** views:

Create a `TabContainerPage` to control a shared tab or,
Place a fake CustomTabBar at the bottom of each tab page to perform the role of a tab bar. When a tab is pressed, replace the current view with the corresponding tab's view.
Here is an example code for the first approach:

Copy code
```swift
public struct TabContainerView: View {
    public var body: some View {
        VStack(spacing: .zero) {
            TabView(selection: .init(
                get: { eventObserver.state.currentTabID },
                set: { eventObserver.state.currentTabID = $0 })) {
                    Tab1Page()
                    .tag(EventState.TapID.main)

                    Tab2Page()
                    .tag(EventState.TapID.myTemplate)

                    Tab3Page()
                    .tag(EventState.TapID.my)
                }
                .tabViewStyle(.page(indexDisplayMode: .never))

            TabBar(
                currentPath: eventObserver.state.currentTabID.rawValue,
                routeAction: {
                    eventObserver.state.currentTabID = .init(rawValue: $0) ?? eventObserver.state.currentTabID
                })
        }
    }
}
```
As shown in the code, you can set up `TabContainerView` to manage your tabs and use TabBar to mimic the functionality of a UITabBar.

Additionally, we are currently developing a TabLinkNavigator that supports UITabViewController internally. This will be an improvement over the existing SingleLinkNavigator and will be released in the near future. 
Please feel free to reach out if you have any further questions.

Thank you. :)

**Comment by farhanadji** [comment]
Hi @97chos thank you for the response.
Actually, I've forked the project and made some adjustments based on our specific needs. To provide context, our app's entry point can be vary; it could be onboarding, login or the logged-in state which is the dashboard with several tabs as i mentioned earlier. Currently, I'm referring to the master branch, which now has a `TabLinkNavigator`- this is exactly what we need. Each tab now has its own navigation controller.

However, there's a challenge. In the Multi-Tab Example app, the entry point directly launches the tab view (`tabNavigator`). In our context, the entry point could be the login page, and then the user navigates to a view that contains the tab view (dashboard). How can we achieve that? Currently, our implementation is similar to the `singleNavigator` in Multi-Tab Example app. In our app, we wrap views inside a navigation controller, and having only one navigation controller (exclude sub). Inside the tab views or its child view, they don't have their own navigation controller. Thus, I'm trying to implement where each child view within the tab view has its own navigation controller. But as you can see in the attached image above, we ended up with two navigation bars; one from the app's navigation controller and another from the navigation controllers within the tab view child views.

This is our current implementation to provide a clearer overview:
![Screenshot 2023-09-25 at 09 51 42](https://github.com/interactord/LinkNavigator/assets/37927649/0001a5b4-2c29-4392-9671-9e2c2ca01170)
And this is what I'm trying to achieve:
![Screenshot 2023-09-25 at 09 53 04](https://github.com/interactord/LinkNavigator/assets/37927649/47cb7f61-7e71-4fdb-8ceb-4c145546cba2)

**Comment by interactord** [comment]
I have uploaded an example to the main branch.

If you only need one navigation, you can use it in single mode.

I have also added a demonstration example.

Please check the single mode.

https://github.com/interactord/LinkNavigator/blob/main/Examples/MultiTab-Example/MultiTab-Example/AppMain.swift

**Comment by r0otx** [comment]
> I have uploaded an example to the main branch.
> 
> I have created it in a way that provides different navigation depending on whether you log in or not, as you intended.
> 
> However, I still have doubts about whether such complex management can really help us solve the problem.
> 
> Wouldn't it be more efficient to use multi-tabs and manage onboarding with modals? I'm considering it.
> 
> The multi-tab you mentioned is the version currently under development.
> 
> It will be somewhat different from now on in the release versions of 1.0.0 and above.
> 
> The example we have created is a very simplified version. As the creator, I don't want to infringe on your freedom.
> 
> I hope you have a good time.
> 
> ![270216693-47cb7f61-7e71-4fdb-8ceb-4c145546cba2-1](https://private-user-images.githubusercontent.com/47267960/270505278-830861ee-dcb6-4a24-b4b2-d1e1e8248407.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODg0NDksIm5iZiI6MTcyODk4ODE0OSwicGF0aCI6Ii80NzI2Nzk2MC8yNzA1MDUyNzgtODMwODYxZWUtZGNiNi00YTI0LWI0YjItZDFlMWU4MjQ4NDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZTExYTlhMzg4ODUwZjA2MmU5OTAzOGU5NGEwNzQzNWJhMzBiMmY1Y2UxY2MwMThkYzQwN2MwMzVlZTVlNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6oi9nhHm7-FS8QNkSKcTcPSJubAKjBA-rt0jzl0ksQI)
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.-.2023-09-26.at.09.53.15.mp4 
> [https://github.com/interactord/LinkNavigator/blob/main/Examples/MultiTab-Example/MultiTab-Example/AppMain.swift\](https://github.com/interactord/LinkNavigator/blob/main/Examples/MultiTab-Example/MultiTab-Example/AppMain.swift%5C)

This link is broken. How I can make next architecture flow.

1. LoginPage(full screen with toolBar) -> OTPPage(full screen with toolBar) -> WrapperBody with tabBar in wrapper -> If click some icons push full screen pages in stack.
