### ISSUE TITLE
iOS 17에서 Large Navigation Title 사용 시 멈춤

### ISSUE THREAD

**Issue by Mercen-Lee** [interactord/LinkNavigator#25]
최상위 View를 제외한 View에서 `.navigationBarTitleDisplayMode(.large)` modifier 사용 시 앱이 멈추고 리소스를 엄청나게 잡아먹습니다.

<img width="257" alt="스크린샷 2023-09-25 13 42 07" src="https://github.com/interactord/LinkNavigator/assets/98750438/0865b388-2ffe-4c7e-be7c-f0e377aa8f91">
<br>
<img width="308" alt="스크린샷 2023-09-25 13 41 58" src="https://github.com/interactord/LinkNavigator/assets/98750438/c9901d13-fc4b-4f9a-beed-371385830eb2">

사진처럼 `.navigationBarTitleDisplayMode(.large)`이 적용된 다음 View로 넘어가기 전에 버튼이 눌린 상태로 화면이 멈춰버립니다.

iOS 17에서만 발생합니다.

**Comment by interactord** [comment]
아래 링크를 참고하시어, 라지 타이틀바를 적용해보실래요?

https://github.com/interactord/LinkNavigator#--extra

**Comment by Mercen-Lee** [comment]
`prefersLargeTitles: true` 파라미터 말씀이시면 이미 적용되어 있습니다.

**Comment by interactord** [comment]
@Mercen-Lee 님 답변이 많이 늦어져서 죄송합니다.
말씀하신대로 navigationBarTitleDisplayMode 적용시, CPU 및 스레드에 대한 락의 대한 문제는 없어 제현이 현재 안되고 있습니다.

혹시 제현이 가능한 예제코드를 공유해주실 수 있을까요?

**Comment by interactord** [comment]
@Mercen-Lee 3주간 대답이 없으셔서 해당 이슈는 닫도록 하곘습니다.
제현이되시거나, 추가적인 내용이 있으시면 해당 이슈 다시 열어주시길 바랍니다.
